CREATE TABLE users (
   id          BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
   username    VARCHAR(50) NOT NULL UNIQUE,
   password    VARCHAR(255) NOT NULL,
   is_admin    BOOLEAN NOT NULL DEFAULT FALSE,
   created_at  TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE invite_tokens (
   id          BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
   token       VARCHAR(255) NOT NULL UNIQUE,
   expires_at  TIMESTAMP NOT NULL,
   used        BOOLEAN NOT NULL DEFAULT FALSE,
   created_at  TIMESTAMP NOT NULL DEFAULT NOW()
);